Upload and read awards data
BloomTech-Labs/urban-pathways-ds pull request #6
Opened 2022-11-22 02:33 UTC by yestrella14

## Description
Created an endpoint to upload xlrd file of awards data. Processed the data from the awards spreadsheet (lines 12-185). Updated the Read endpoint to display data from Rows 13-185 with the appropriate column headers. Created an Schema class with the column headers and appropriate data types.

Requirements.txt was updated.

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-12-02 02:37 UTC, nlittlepoole requested changes
Good first pass

2022-12-02 02:37 UTC, nlittlepoole commented on app/mongo_files/api.py
> +# @API.post("/upload-file")
we probably want to delete dead code. However you should try to use the `(file: UploadFile):` as provided here instead of a filename.

2022-12-02 02:37 UTC, nlittlepoole commented on app/services.py
> +    f = os.path.realpath(os.path.join("fixtures", f.filename))
we want to replace this with opening the actual file bytes. You can do this by following the example in this [stackoverflow post.](https://stackoverflow.com/questions/20635778/using-openpyxl-to-read-file-from-memory)

2022-12-02 02:37 UTC, nlittlepoole commented on app/services.py
> +    rows = awards_sheet.iter_rows(13, 3000, 0, 43, values_only=True)
so here you've fixed the row counts. But each month users are going to upload a new file. There may be more or less rows of data in the file than the last time. So this needs to updated to work such that you iterate through the rows, and check for some condition that tells you to stop iterating.

2022-12-02 02:37 UTC, nlittlepoole commented on app/services.py
> +    q = requests.get("http://127.0.0.1:8000/")
this should be taken out. If you want to test this once the server is running you should use a separate terminal window and either a Python repl or curl

2022-12-06 07:10 UTC, jinjahninjah requested changes

2022-12-06 07:10 UTC, jinjahninjah commented on .gitignore
> +*.db
Thank you for this! 👍

2022-12-06 07:10 UTC, jinjahninjah commented on app/mongo_files/api.py
> +# @API.post("/upload-file")
This is in the Mongo interface so we can just remove all of these changes as they are not needed 👍

2022-12-06 07:10 UTC, jinjahninjah commented on app/main.py
> +@app.post("/upload-file")
I would change this to something like `"/upload-awards-file"` as we are going to add another endpoint soon 👍

2022-12-13 03:44 UTC, jinjahninjah approved these changes
🚢

2022-12-16 16:51 UTC, merged